### PR TITLE
development: add docker image for faster start

### PR DESCRIPTION
**Pull request by henriquekano**
## Description

 Adds a docker compose yml for first timers, as they will only have to install docker and docker compose.

 ## Tests

I only checked if the site is up and running after the setup. A exception was raised when I tried making a donation, but I didn't set any configs regarding the payment gateway.

 ## Other

Not sure what's up with the generated migration, but since it's a migration, I just added it.

### CODE REVIEW

**Comment by fernandosjp** [comment]
@henriquekano this is a great contribution! I am thinking on small adjustsments and I need some help to make it work on my side to be able to check if all tests keep passing.

**Small changes:**
- [ ] fix setup database commands
- [ ] remove migration file (there is no need. This file will be created when you run the cmd python manage.py makemigrations in the start.sh script)
 
In my computer I'm getting the error bellow. Do you have any clue why? Postgres image is working fine but something happens when trying to build django image. 
 
image

**Comment by henriquekano** [comment]
@fernandosjp not sure why the error occurred. But checking the the screenshot you took, i'd try two things:
1 - run the container outside a venv
2 - add the user you are using to the `docker` group, so you don't have to sudo all your docker commands :/ - I added a section in the readme commenting this, for more information

**Comment by fernandosjp** [comment]
I am almost there @henriquekano! 

1- it was a bug of docker-compose 1.20.0 related to virtualenv. Updated and it is working
2- done and it is much better to avoid using `sudo` everytime

Now I am actually stuck because the database script returns an error saying that the 'admin' role does not exist. Where in the process are initializing the database? I think I' at the same page as the errors that are happening inside Travis CI. Let's try to find out? If you have any hint I will keep helping in the process!

**Comment by henriquekano** [comment]
@fernandosjp basically, if you check the `docker-compose.yml`, I just run the start.sh script after the start of the django container and using the default database in the db container, I run the migrationse'.

I think the problem with travis is: since I changed the dev settings to match the docker service's, it doesn't point to the localhost anymore.

Now, why it's not running in your setup is still a mystery. Try going in the postgres service manually (`docker-compose exec postgres bash` - after running the `up` command) and check if the admin user is there.

**Pull request closed without merging**
